name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, setup-ci-cd, master]

jobs:
  playwright-test:
    name: "Playwright Tests - Shard ${{ matrix.shard }}"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Container Cleanup
        continue-on-error: true
        run: docker rm playwright_test --force

      - name: Build Docker image
        run: docker build --file Dockerfile -t playwright_image

      - name: Run docker container
        run: docker run --rm -i --entrypoint="npx" --name playwright_test playwright_image playwright test --shard ${{matrix.shard}}

      - name: Copy test results
        run: docker cp dockercontainer:./tests/playwright-report playwright-report

      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      # - name: Install dependencies
      #   run: npm ci

      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps

      # - name: Run Playwright tests
      #   run: npx playwright test --shard ${{ matrix.shard }}

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: blob-report
      #     path: blob-report/
      #     retention-days: 30

  # merge-reports:
  #   if: always()
  #   needs: [playwright-test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Download blob reports
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: blob-report
  #         path: blob-report/

  #     - name: Merge into HTML report
  #       run: npx playwright merge-reports --reporter html ./blob-report

  #     - name: Upload HTML reporter
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: merged-html-report-${{ github.run_attempt}}
  #         path: playwright-report
